tasks:
  # KUBE_CONFIG is kubernetes auth info. https://www.linode.com/docs/guides/deploy-and-manage-a-cluster-with-linode-kubernetes-engine-a-tutorial/
  # to update KUBE_CONFIG: `gp env KUBE_CONFIG=$(base64 -w 0 new-config-file.yaml)`
  # https://gitpod.io/variables
  # https://github.com/erosson/multiplayer/settings/secrets/actions
  - before: |
      ./.gp/install-kubectl.sh
      ./.gp/install-helm.sh
      ./.gp/config-kube.sh
    command: |
      kubectl version --client
      helm version --client