# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chrom-graph.erosson.org
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=ghcr.io/erosson/chrom-graph:latest
    argocd-image-updater.argoproj.io/main.update-strategy: digest
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/erosson/kubernetes.git
    targetRevision: HEAD
    path: packages/erosson/chrom-graph
  destination:
    server: https://kubernetes.default.svc
    namespace: default