apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: chrom-graph-image

commonLabels:
  app.kubernetes.io/instance: chrom-graph.erosson.org

# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md
images:
- name: ghcr.io/erosson/chrom-graph
  newTag: latest

resources:
- www.yml
- argocd.yml