# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-letsencrypt-staging

commonLabels:
  app.kubernetes.io/instance: test-letsencrypt-staging.erosson.org

resources:
- argocd.yml
- test-letsencrypt-staging.yml