# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-multiplayer-image

commonLabels:
  app.kubernetes.io/instance: test-multiplayer.erosson.org

images:
- name: ghcr.io/erosson/multiplayer/server
  newTag: latest
- name: ghcr.io/erosson/multiplayer/www
  newTag: latest
  

resources:
- dont-autosync/argocd.yml
- server.yml
- www.yml