# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/image.md
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: test-multiplayer-image

images:
- name: ghcr.io/erosson/multiplayer/server
  newTag: haha
- name: ghcr.io/erosson/multiplayer/www
  newTag: haha
  

resources:
- server.yml
- www.yml