# based on https://www.linode.com/docs/guides/how-to-deploy-nginx-ingress-on-linode-kubernetes-engine/
#
# also learned from https://mbuffett.com/posts/kubernetes-setup/
# https://news.ycombinator.com/item?id=26502900
apiVersion: v1
kind: Service
metadata:
  name: hello-one
  # annotations:
    # external-dns.alpha.kubernetes.io/hostname: k8s-test-hello1.erosson.org
    #external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-one
  template:
    metadata:
      labels:
        app: hello-one
    spec:
      containers:
      - name: hello-ingress
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-new-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s-test-hello1.erosson.org
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8s-test-hello1.erosson.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-one
            port:
              number: 80