# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-test-hello1.erosson.org
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/erosson/kubernetes.git
    targetRevision: HEAD
    path: examples/k8s-test-hello1.erosson.org
  destination:
    server: https://kubernetes.default.svc
    namespace: default